apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "finguard.fullname" . }}-config
  labels:
    {{- include "finguard.labels" . | nindent 4 }}
data:
  OPENCOST_URL: {{ .Values.opencost.url | quote }}
  FINGUARD_LOG_LEVEL: {{ .Values.env.FINGUARD_LOG_LEVEL | quote }}
